; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
framework = arduino
build_unflags = -std=gnu++11
; board_build.partitions = huge_app.csv
board_build.partitions = no_fs.csv
upload_speed = 921600
monitor_speed = 115200
lib_deps = h2zero/NimBLE-Arduino@^2.5.0
build_flags =
    -DWIFI_SSID=\"TheMatrix\"
    -DWIFI_PASSWORD=\"Whatever!88\"

[env:wrover]
board = esp-wrover-kit
board_build.psram = enabled
build_flags =
    ${env.build_flags}
    -std=gnu++17
    -DOTA_HOSTNAME=\"ble-wrover-1\"
    -DOTA_PASSWORD=\"wrover-1\"
    -DDEVICE_IP=192,168,1,160
monitor_port = COM5
upload_protocol = espota
upload_port = 192.168.1.160
upload_flags = --auth=wrover-1
[env:wrover-com]
extends = env:wrover
upload_protocol = esptool
; upload_port = COM5
upload_flags =

[env:c3]
board = esp32-c3-devkitm-1
build_flags =
    ${env.build_flags}
    -std=gnu++17
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DOTA_HOSTNAME=\"ble-c3-1\"
    -DOTA_PASSWORD=\"c3-1\"
    -DDEVICE_IP=192,168,1,161
monitor_port = COM6
upload_protocol = espota
upload_port = 192.168.1.161
upload_flags = --auth=c3-1
[env:c3-com]
extends = env:c3
upload_protocol = esptool
; upload_port = COM6
upload_flags =